### ISSUE TITLE
Error output on transaction failure

### ISSUE THREAD

**Issue by jfornoff** [commanded/commanded-ecto-projections#9]
Hi there,

we noticed that Projections fail somewhat silently (the process just exits but yields no explanation as to why) when an Error is raised, e.g., a `:not_null_violation`.

This seems to be caused by the fact that Errors are not handled and bubble up unintercepted, which eventually causes the process to exit.

To improve debuggability, it'd be nice to have some logging of Errors before they are reraised and preserve the old behavior of the process dying.

I'd be happy to contribute a patch and add this, it's pretty straightforward, but I'm not sure if this would belong here or in `commanded` in the generic event handler and would love to hear your input on this.

Best,
Jan

**Comment by slashdotdash** [comment]
An Ecto projection is a Commanded event handler. This [logs an error](https://github.com/commanded/commanded/blob/4964f624f3da0976792b4aa791702ad11452a9e0/lib/commanded/event/handler.ex#L317) whenever an event handler fails to handle an event by returning an `{:error, reason}` tagged tuple.

Are you saying this doesn't happen for certain database errors?

**Comment by jfornoff** [comment]
In my understanding, this does not happen when an error is raised.
So the distinction we need to draw is `raise SomeError` vs returning `{:error, :some_error}`, the second case is covered in the code that you linked, but I don't think the first one is.

**Comment by slashdotdash** [comment]
@jfornoff Thanks for the additional feedback. 

I think the change required for Commanded is to include a `rescue` block to the [`handle_info/2` callback function](https://github.com/commanded/commanded/blob/4964f624f3da0976792b4aa791702ad11452a9e0/lib/commanded/event/handler.ex#L276) in the event handler module. This can catch any exceptions, log an error, and then stop the process. A simple test for this would be to define an event handler that simply raises an exception. 

It might be worth moving the error logging from the `handle_event/2` function to `handle_info/2` so that it's consistent with the newly added rescue block. 

Does that make sense, and if so would you like to attempt a pull request?

**Comment by jfornoff** [comment]
That sounds reasonable to me, I'll prepare a PR 👍

**Comment by jfornoff** [comment]
Upon throwing together a PR I was able to verify in the tests that the raised Errors are actually logged just fine in plain `commanded` and it turns out one of our sub-applications disabled parts of Elixir logging.

So it's an error on our end, apologies. 😅
